[project]
name = "ww-manager"
version = "2.1.0"
description = "鸣潮 (Wuthering Waves) 命令行管理器"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["typer", "tqdm", "certifi"]

[project.scripts]
# 指向 cli.py 中的 app
ww = "cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
